In [1]:
import seaborn as sb
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from scipy import stats


In [2]:
#kaggle Heart Disease Cleveland

df = pd.read_csv('Heart_disease_cleveland_new.csv')

In [3]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   0       145   233    1        2      150      0      2.3      2   
1   67    1   3       160   286    0        2      108      1      1.5      1   
2   67    1   3       120   229    0        2      129      1      2.6      1   
3   37    1   2       130   250    0        0      187      0      3.5      2   
4   41    0   1       130   204    0        2      172      0      1.4      0   

   ca  thal  target  
0   0     2       0  
1   3     1       1  
2   2     3       1  
3   0     1       0  
4   0     1       0

In [4]:
df.info()
#no missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [5]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.438944    0.679868    2.158416  131.689769  246.693069    0.148515   
std      9.038662    0.467299    0.960126   17.599748   51.776918    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     48.000000    0.000000    2.000000  120.000000  211.000000    0.000000   
50%     56.000000    1.000000    2.000000  130.000000  241.000000    0.000000   
75%     61.000000    1.000000    3.000000  140.000000  275.000000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.990099  149.607261    0.326733    1.039604    0.600660    0.663366   
std      0.994971   22.875003    0.469794    1.161075    0.616226    0.934375   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    0.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      2.000000  166.000000    1.000000    1.600000    1.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    3.000000   

             thal      target  
count  303.000000  303.000000  
mean     1.831683    0.458746  
std      0.956705    0.499120  
min      1.000000    0.000000  
25%      1.000000    0.000000  
50%      1.000000    0.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [6]:
df[df['target']==1].target.count()

139

In [7]:
df[df['target']==0].target.count()

164

In [8]:
columns=df.columns
for column in columns:
    zscores = stats.zscore(df[column])
    zscore_threshold = 3
    outliers = df[abs(zscores) > zscore_threshold]
    print (column)
    print(outliers)

age
Empty DataFrame
Columns: [age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal, target]
Index: []
sex
Empty DataFrame
Columns: [age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal, target]
Index: []
cp
Empty DataFrame
Columns: [age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal, target]
Index: []
trestbps
     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
126   56    0   3       200   288    1        2      133      1      4.0   
188   54    1   1       192   283    0        2      195      0      0.0   

     slope  ca  thal  target  
126      2   2     3       1  
188      0   1     3       1  
chol
     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
48    65    0   2       140   417    1        2      157      0      0.8   
121   63    0   3       150   407    0        2      154      0      4.0   
152   67    0   2       115   564  

In [9]:
#changing outlaires to be median
df.loc[126,'trestbps']=df.trestbps.median()
df.loc[188,'trestbps']=df.trestbps.median()

df.loc[48,'chol']=df.chol.median()
df.loc[121,'chol']=df.chol.median()
df.loc[152,'chol']=df.chol.median()
df.loc[181,'chol']=df.chol.median()

df.loc[91,'oldpeak']=df.oldpeak.median()
df.loc[123,'oldpeak']=df.oldpeak.median()

       
df.loc[245,'thalach']=df.thalach.median()


In [10]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split


In [11]:
X=df.drop('target',axis=1)
y=df['target']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(\
    X, y, test_size=0.30, random_state=101)

In [13]:
sc=StandardScaler()

In [14]:
X_train_transformed=pd.DataFrame(sc.fit_transform(X_train),columns=X_train.columns,index=X_train.index)

In [15]:
X_test_transformed=pd.DataFrame(sc.transform(X_test),columns=X_test.columns,index=X_test.index)

In [16]:
X_train_transformed.describe()

age           sex            cp      trestbps          chol  \
count  2.120000e+02  2.120000e+02  2.120000e+02  2.120000e+02  2.120000e+02   
mean  -2.106543e-16  1.550123e-16 -1.340647e-16  2.812216e-16  1.120697e-16   
std    1.002367e+00  1.002367e+00  1.002367e+00  1.002367e+00  1.002367e+00   
min   -2.879927e+00 -1.424279e+00 -2.256216e+00 -2.157187e+00 -2.437572e+00   
25%   -7.344960e-01 -1.424279e+00 -1.720426e-01 -6.199648e-01 -7.025142e-01   
50%    1.688435e-01  7.021095e-01 -1.720426e-01 -2.872531e-02 -9.524402e-02   
75%    7.334308e-01  7.021095e-01  8.700442e-01  5.625142e-01  6.638437e-01   
max    2.201358e+00  7.021095e-01  8.700442e-01  2.927472e+00  3.266430e+00   

                fbs       restecg       thalach         exang       oldpeak  \
count  2.120000e+02  2.120000e+02  2.120000e+02  2.120000e+02  2.120000e+02   
mean   1.110223e-16  6.807971e-18  4.456603e-16  2.827927e-17  1.118078e-16   
std    1.002367e+00  1.002367e+00  1.002367e+00  1.002367e+00  1.002367e+00   
min   -4.216370e-01 -1.016654e+00 -2.679691e+00 -6.797565e-01 -9.136086e-01   
25%   -4.216370e-01 -1.016654e+00 -7.209708e-01 -6.797565e-01 -9.136086e-01   
50%   -4.216370e-01  9.882819e-01  1.216070e-01 -6.797565e-01 -2.300144e-01   
75%   -4.216370e-01  9.882819e-01  6.906207e-01  1.471115e+00  5.447257e-01   
max    2.371708e+00  9.882819e-01  2.310121e+00  1.471115e+00  3.096811e+00   

              slope            ca          thal  
count  2.120000e+02  2.120000e+02  2.120000e+02  
mean   4.032414e-17  1.047380e-18 -2.325184e-16  
std    1.002367e+00  1.002367e+00  1.002367e+00  
min   -9.842837e-01 -6.983963e-01 -8.999722e-01  
25%   -9.842837e-01 -6.983963e-01 -8.999722e-01  
50%    6.208559e-01 -6.983963e-01 -8.999722e-01  
75%    6.208559e-01  3.745024e-01  1.185209e+00  
max    2.225996e+00  2.520300e+00  1.185209e+00

In [17]:
#training a decisionTree model
from sklearn.tree import DecisionTreeClassifier

In [18]:
dtree = DecisionTreeClassifier()

In [19]:
dtree.fit(X_train_transformed, y_train)

DecisionTreeClassifier()

In [20]:
dtree.score(X_train_transformed,y_train)

1.0

In [21]:
dtree.score(X_test_transformed,y_test)

0.7582417582417582

In [22]:
pred = dtree.predict(X_test_transformed)

In [23]:
from sklearn.metrics import classification_report, confusion_matrix

In [24]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.75      0.82      0.78        49
           1       0.76      0.69      0.72        42

    accuracy                           0.76        91
   macro avg       0.76      0.75      0.75        91
weighted avg       0.76      0.76      0.76        91



In [25]:
print(confusion_matrix(y_test, pred))

[[40  9]
 [13 29]]


In [26]:
#training a RandomForest model
from sklearn.ensemble import RandomForestClassifier

In [27]:
rfc = RandomForestClassifier(n_estimators=100)

In [28]:
rfc.fit(X_train_transformed, y_train)

RandomForestClassifier()

In [29]:
pred = rfc.predict(X_test_transformed)

In [30]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.76      0.86      0.81        49
           1       0.81      0.69      0.74        42

    accuracy                           0.78        91
   macro avg       0.78      0.77      0.78        91
weighted avg       0.78      0.78      0.78        91



In [31]:
print(confusion_matrix(y_test, pred))

[[42  7]
 [13 29]]


In [32]:
#finding best params for randomforest model
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV

In [33]:
rf_classifier = RandomForestClassifier()

param_grid = {
    'n_estimators': [50,100, 200],  
    'max_depth': [None, 5, 10],  
    'min_samples_split': [2, 5, 10],  
    'min_samples_leaf': [1, 2, 4] 
}

grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, cv=5)
grid_search.fit(X_train_transformed, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [None, 5, 10],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [50, 100, 200]})

In [34]:
grid_search.best_params_

{'max_depth': None,
 'min_samples_leaf': 2,
 'min_samples_split': 5,
 'n_estimators': 50}

In [35]:
rfc2 = RandomForestClassifier(n_estimators=200,min_samples_leaf=4, min_samples_split=5)
rfc2.fit(X_train_transformed, y_train)
pred = rfc2.predict(X_test_transformed)
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.81      0.88      0.84        49
           1       0.84      0.76      0.80        42

    accuracy                           0.82        91
   macro avg       0.83      0.82      0.82        91
weighted avg       0.83      0.82      0.82        91



In [36]:
rfc2.feature_importances_

array([0.06472399, 0.02417201, 0.18695076, 0.04590299, 0.04644994,
       0.00225974, 0.01436002, 0.14252851, 0.07261134, 0.0911383 ,
       0.03918505, 0.09452328, 0.17519408])

In [37]:
print(confusion_matrix(y_test,pred))

[[43  6]
 [10 32]]


In [38]:
X2_train_transformed=X_train_transformed.drop(['fbs','sex','slope'],axis=1)
rfc2 = RandomForestClassifier(n_estimators=100,min_samples_leaf=4, min_samples_split=5)
rfc2.fit(X_train_transformed, y_train)
pred = rfc2.predict(X_test_transformed)
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.81      0.86      0.83        49
           1       0.82      0.76      0.79        42

    accuracy                           0.81        91
   macro avg       0.81      0.81      0.81        91
weighted avg       0.81      0.81      0.81        91



In [39]:
print(confusion_matrix(y_test,pred))

[[42  7]
 [10 32]]


In [51]:
#knn model
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=35)
knn.fit(X_train_transformed,y_train)
pred = knn.predict(X_test_transformed)

C:\Users\DIKLARE\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [53]:
print(confusion_matrix(y_test,pred))

[[45  4]
 [11 31]]


In [42]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.80      0.92      0.86        49
           1       0.89      0.74      0.81        42

    accuracy                           0.84        91
   macro avg       0.84      0.83      0.83        91
weighted avg       0.84      0.84      0.83        91



In [96]:
#tring to improve the recall
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=35)
knn.fit(X_train_transformed,y_train)
predicted_probabilities = knn.predict_proba(X_test_transformed)[:, 1]  # Probabilities for class 1
threshold = 0.3
predicted_classes = (predicted_probabilities > threshold).astype(int)

In [97]:
print(confusion_matrix(y_test,predicted_classes))

[[34 15]
 [ 4 38]]


In [98]:
print(classification_report(y_test,predicted_classes))

              precision    recall  f1-score   support

           0       0.89      0.69      0.78        49
           1       0.72      0.90      0.80        42

    accuracy                           0.79        91
   macro avg       0.81      0.80      0.79        91
weighted avg       0.81      0.79      0.79        91



In [111]:
#svm model
from sklearn import svm
svm = svm.SVC(kernel='linear')
svm.fit(X_train_transformed, y_train)

pred = svm.predict(X_test_transformed)
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.81      0.88      0.84        49
           1       0.84      0.76      0.80        42

    accuracy                           0.82        91
   macro avg       0.83      0.82      0.82        91
weighted avg       0.83      0.82      0.82        91



In [112]:
print(confusion_matrix(y_test, pred))

[[43  6]
 [10 32]]


In [43]:
#mlp model
from sklearn.neural_network import MLPClassifier
mlp=MLPClassifier(hidden_layer_sizes=(70,70,70))
mlp.fit(X_train_transformed,y_train)
pred=mlp.predict(X_test_transformed)
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.80      0.80      0.80        49
           1       0.76      0.76      0.76        42

    accuracy                           0.78        91
   macro avg       0.78      0.78      0.78        91
weighted avg       0.78      0.78      0.78        91



C:\Users\DIKLARE\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [44]:
print(confusion_matrix(y_test, pred))

[[39 10]
 [10 32]]


In [45]:
#voting with the best models
from sklearn.ensemble import VotingClassifier

emodel = VotingClassifier(estimators=[('mlp', mlp), ('knn', knn),('rfc2',rfc)],
                        voting='hard')
emodel.fit(X_train_transformed, y_train)

C:\Users\DIKLARE\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


VotingClassifier(estimators=[('mlp',
                              MLPClassifier(hidden_layer_sizes=(70, 70, 70))),
                             ('knn', KNeighborsClassifier(n_neighbors=35)),
                             ('rfc2', RandomForestClassifier())])

In [46]:
print(confusion_matrix(y_test, pred))

[[39 10]
 [10 32]]


In [47]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.80      0.80      0.80        49
           1       0.76      0.76      0.76        42

    accuracy                           0.78        91
   macro avg       0.78      0.78      0.78        91
weighted avg       0.78      0.78      0.78        91

